# Generated by Django 4.0.4 on 2022-04-11 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
