# Generated by Django 4.0.4 on 2022-04-11 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
