# Generated by Django 4.0.4 on 2022-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='day',
        ),
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
